name: Build and Run

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
      - name: Run and collect coverage
        run: |
          coverage run --branch bm_reading_test.py
          coverage html
      - name: Upload coverage
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: ./htmlcov
          retention-days: 1
